//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketing_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_tbl
    {
        public string CategoryID { get; set; }
        public string CategoryType { get; set; }
        public string UserID { get; set; }
    
        public virtual Users_tbl Users_tbl { get; set; }
    }
}
