//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketing_Tool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Marketing_ToolsEntities : DbContext
    {
        public Marketing_ToolsEntities()
            : base("name=Marketing_ToolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_tbl> Category_tbl { get; set; }
        public virtual DbSet<Student_category> Student_category { get; set; }
        public virtual DbSet<Student_tbl> Student_tbl { get; set; }
        public virtual DbSet<Student_user> Student_user { get; set; }
        public virtual DbSet<Users_tbl> Users_tbl { get; set; }
        public virtual DbSet<CategoryList> CategoryLists { get; set; }
    }
}
