//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketing_Tool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student_tbl
    {
        [Required(ErrorMessage = "This field is requied")]
        public string StudentID { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string StudentName { get; set; }

        [Required(ErrorMessage = "Please enter valied email", AllowEmptyStrings = false)]
        [EmailAddress(ErrorMessage = "Enter valied email!")]   
        public string StudentEmail { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string NIC { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public System.DateTime Dob { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string Addresss { get; set; }

        //[RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        [Required(ErrorMessage = "This field is requied")]
        public int ContactNumber { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string Category { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string Action { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string Response { get; set; }

        [Required(ErrorMessage = "This field is requied")]
        public string comment1 { get; set; }
      
        public string comment2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> NextCallingDate { get; set; }
    
        public virtual Users_tbl Users_tbl { get; set; }
    }
}
