//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketing_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_tbl()
        {
            this.Category_tbl = new HashSet<Category_tbl>();
            this.Student_tbl = new HashSet<Student_tbl>();
        }
    
        public string UserID { get; set; }
        public string UserType { get; set; }
        public string FullName { get; set; }
        public string UserEmail { get; set; }
        public string NIC { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address { get; set; }
        public int ContactNumber { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_tbl> Category_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_tbl> Student_tbl { get; set; }
    }
}
